[package]
name = "op_agent"
version = "0.2.0"
authors = ["Jean"]
edition = "2018"
build = "build.rs"

[package.metadata.winres]
OriginalFilename = "OP Agent.exe"
LegalCopyright = "Copyright © 2020"
FileDescription = "Agent Software Tool"
CompanyName = "Boo Productions"

[dependencies]
winreg = "0.6"
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0" 

[build-dependencies]
winres = "0.1"
