[package]
name = "op_agent"
version = "0.1.1"
authors = ["Jean"]
edition = "2018"
build = "build.rs"

[package.metadata.winres]
OriginalFilename = "OP Agent.exe"
LegalCopyright = "Copyright © 2020"
FileDescription = "Agent Software Tool"
CompanyName = "Boo Productions"

[dependencies]
winreg = "0.6.2"

[build-dependencies]
winres = "0.1.11"
